# Generated by Django 2.0 on 2017-12-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20171214_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ipadd',
            field=models.GenericIPAddressField(),
        ),
    ]
