# Generated by Django 2.0 on 2017-12-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20171215_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientmac', models.CharField(max_length=19)),
                ('clientipadd', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='enable',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
    ]
