# Generated by Django 2.0 on 2017-12-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20171216_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientipadd',
            new_name='ipadd',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientmac',
            new_name='mac',
        ),
    ]
