# Generated by Django 2.0 on 2017-12-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_devicefacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mac',
            field=models.CharField(max_length=19, unique=True),
        ),
    ]
